name: Backend

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Install dependencies
        run: |
          cd backend/
          go version
          go get -d ./...

      - name: Run vet & lint
        run: |
          cd backend/
          go vet .

      - name: Run build
        run: |
          cd backend/
          go build .
