name: Test & Deploy Backend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Install dependencies
        run: |
          cd backend/
          go version
          go get -d ./...

      - name: Run build & Generate package
        run: |
          cd backend/
          GOOS=linux GOARCH=amd64 go build -o bin/application
          zip -r eb-latest.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: twclone backend
          environment_name: Twclonebackend-env
          version_label: twc-latest
          region: us-east-1
          deployment_package: backend/eb-latest.zip
