name: Frontend Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
      - name: Install dependencies
        run: |
          cd client/
          npm i yarn -g
          yarn install

      - name: Run build
        run: |
          yarn build
